//
//  DetailCharacterScenePresenter.swift
//  MarvelHeroes
//
//  Created by Humberto C Trujano Chavez on 1/2/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailCharacterScenePresentationLogic
{
}

class DetailCharacterScenePresenter: DetailCharacterScenePresentationLogic
{
  weak var viewController: DetailCharacterSceneDisplayLogic?
  
  // MARK: Do something
  
}
