//
//  DetailCharacterSceneRouter.swift
//  MarvelHeroes
//
//  Created by Humberto C Trujano Chavez on 1/2/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SafariServices

@objc protocol DetailCharacterSceneRoutingLogic{
    func routeToSafariVC(urlStr: String)
}

protocol DetailCharacterSceneDataPassing
{
  var dataStore: DetailCharacterSceneDataStore? { get }
}

class DetailCharacterSceneRouter: NSObject, DetailCharacterSceneRoutingLogic, DetailCharacterSceneDataPassing
{
  weak var viewController: DetailCharacterSceneViewController?
  var dataStore: DetailCharacterSceneDataStore?
  
  // MARK: Routing
  
    func routeToSafariVC(urlStr: String){
        
        if let url = URL(string: urlStr) {
            let safariVC = SFSafariViewController(url: url, configuration: SFSafariViewController.Configuration.init())
            safariVC.delegate = viewController

            viewController?.present(safariVC, animated: true, completion: nil)
        }
    }
}
