//
//  DetailCharacterSceneInteractor.swift
//  MarvelHeroes
//
//  Created by Humberto C Trujano Chavez on 1/2/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailCharacterSceneBusinessLogic
{
}

protocol DetailCharacterSceneDataStore
{
    var detailCharacterInfo: DetailCharacterModel? {get set}
}

class DetailCharacterSceneInteractor: DetailCharacterSceneBusinessLogic, DetailCharacterSceneDataStore
{
    var presenter: DetailCharacterScenePresentationLogic?
    var detailCharacterInfo: DetailCharacterModel? = nil
    
    // MARK: Do DetailCharacterSceneBusinessLogic
    
}
