//
//  ListCharactersSceneRouter.swift
//  MarvelHeroes
//
//  Created by Humberto C Trujano Chavez on 30/1/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListCharactersSceneRoutingLogic{
    func routeToDetailCharacterScene()
}

protocol ListCharactersSceneDataPassing{
    var dataStore: ListCharactersSceneDataStore? { get }
    
    func passDataToDetailCharacterScene(segue: UIStoryboardSegue)
}

class ListCharactersSceneRouter: NSObject, ListCharactersSceneRoutingLogic, ListCharactersSceneDataPassing
{
    weak var viewController: ListCharactersSceneViewController?
    var dataStore: ListCharactersSceneDataStore?
    
    // MARK: Routing
    
    func routeToDetailCharacterScene(){
        viewController?.performSegue(withIdentifier: ListCharactersSceneViewController.idSegue_ListToDetailCharacter, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToDetailCharacterScene(segue: UIStoryboardSegue){
        let destinationVC = segue.destination as! DetailCharacterSceneViewController
        var destinationDS = destinationVC.router!.dataStore!
        destinationDS.detailCharacterInfo = dataStore?.detailCharacterInfo
    }
}
