//
//  ListCharactersScenePresenter.swift
//  MarvelHeroes
//
//  Created by Humberto C Trujano Chavez on 30/1/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListCharactersScenePresentationLogic
{
    func presentListCharactersOk(listInfo: ListCharactersInfo)
    func presentListCharactersErrorReloading()
    func presentNextListCharactersPage(listInfo: ListCharactersInfo)
    func stopListCharactersPagination()
    func presentDetailCharacter(detailInfo: DetailCharacterInfo)
    func presentDetailCharacterErrorLoading()

    func presentStartActivity()
    func presentStopActivity()

}

class ListCharactersScenePresenter: ListCharactersScenePresentationLogic
{
    weak var viewController: ListCharactersSceneDisplayLogic?
    
    // MARK: Do ListCharactersScenePresentationLogic
        
    func presentListCharactersOk(listInfo: ListCharactersInfo){
        viewController?.reloadTable(listInfo: listInfo)
    }
    
    func presentListCharactersErrorReloading(){
        viewController?.showLoadErrorViewByListCharacters()
    }

    func presentStartActivity() {
        viewController?.startActivityIndicator()
    }
    
    func presentStopActivity() {
        viewController?.stopActivityIndicator()
    }
    
    func presentNextListCharactersPage(listInfo: ListCharactersInfo){
        viewController?.updateNextPaginationPage(listInfo: listInfo)
    }
    
    func stopListCharactersPagination(){
        viewController?.stopPagination()
    }

    func presentDetailCharacter(detailInfo: DetailCharacterInfo){
        viewController?.showDetailCharacter(detailInfo: detailInfo)
    }
    
    func presentDetailCharacterErrorLoading(){
        viewController?.showLoadErrorViewByDetailCharacter()
    }

}
